### ISSUE TITLE
Nick can you update this extension compatible to sym2.4?

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/incrementnumberfield#5]
Debugging:<error>MySQL Fout (1146): Table '.sym_entries_data_' doesn't exist in query: UPDATE sym_entries_data_ SET  `value` = '115' WHERE entry_id=165 on 867 of file \symphony\lib\toolkit\class.mysql.php</error>

Or in the Symphony
Symphony Fatal Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
An error occurred while attempting to execute the following query
UPDATE sym_entries_data_108 SET value = (value + 1) WHERE value >=

I reinstalled the field but same problem.

Thank you!

**Comment by nitriques** [comment]
Should be working now.
